baseURL = 'https://eri24816.github.io/Blog_Hugo/'
languageCode = 'en-us'
title = "eri24816's blog"
theme = "chunky-poster"

summaryLength=10

[Params]
    customCSS = ["custom.css"]
    customJS = ["custom.js"]
    share = true

